# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties (Minecraft 1.21.1)
minecraft_version=26.2
yarn_mappings=unused
loader_version=0.19.3
fabric_version=0.158.0+26.2

# Mod Properties
mod_version=1.0.0
maven_group=net.coreprotect
archives_base_name=coreprotect-fabric-26.2

