# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties (Minecraft 26.1.2)
minecraft_version=26.1.2
yarn_mappings=unused
loader_version=0.19.3
fabric_version=0.155.2+26.1.2

# Mod Properties
mod_version=1.8.2
maven_group=net.coreprotect
archives_base_name=coreprotect-fabric-26.1.2

